Added Hindi translation of README.md
fityannugroho/idn-area pull request #194
Opened 2023-10-05 12:29 UTC by CharithaCS

## PR Checklist

Please check if your PR fulfills the following requirements:

> Put "x" to check

- [ ] The commit message follows our [Contributing Guidelines](https://github.com/fityannugroho/idn-area/blob/main/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (**optional**, for bug fixes or features)
- [ ] Docs have been added / updated (**optional**, for bug fixes or features)

## PR Type

What kind of change does this PR introduce?

> Please check any kind of changes that applies to this PR using "x"

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] *..... (describe the other type)*

## What is the current behavior?

> Please describe the current behavior that you are modifying, or link to a relevant issue.

Issue Number: *..... (put `N/A` if there are no relevant issue)*

*..... (explain here)*

## What is the new behavior?

*..... (explain here)*

## Other information

*..... (explain here, or put `None`)*

2023-10-05 14:48 UTC, fityannugroho commented
Will request hindi reviewer.

2023-10-05 14:50 UTC, CharithaCS commented
Alright, Thanks!

On Thu, 5 Oct, 2023, 20:18 Fityan, ***@***.***> wrote:

> Will request hindi reviewer.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fityannugroho/idn-area/pull/194#issuecomment-1749061350>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A752EJ3JWL5ZR2WAUV5IMU3X53CC3AVCNFSM6AAAAAA5UFVUGSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONBZGA3DCMZVGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-05 15:22 UTC, fityannugroho requested changes
I only found one thing that needs to be fixed

2023-10-05 15:22 UTC, fityannugroho commented on docs/README_hi.md
> +एपीआई जो इंडोनेशिया के **प्रशासनिक क्षेत्रों**, प्रांत, रीजेंसी, जिले से लेकर ग्राम स्तर तक की जानकारी प्रदान करता है। यह [संस्करण 1.1.0] से द्वीप डेटा भी प्रदान करता है (https://github.com/fityannug
This link will not rendered well. Can you fix it?

2023-10-05 16:03 UTC, CharithaCS commented
Sure, Thanks for bringing this to my attention.

On Thu, 5 Oct, 2023, 20:52 Fityan, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I only found one thing that needs to be fixed
> ------------------------------
>
> In docs/README_hi.md
> <https://github.com/fityannugroho/idn-area/pull/194#discussion_r1347574728>
> :
>
> > @@ -0,0 +1,322 @@
> +<h1 align="">इन्डोनेशियाई क्षेत्र एपीआई (<i>API Wilayah Indonesia</i>)</h1>
> +
> +<p>
> +  <a href="https://nestjs.com"><img alt="नेस्ट जे एस" src="https://img.shields.io/badge/-NestJS-ea2845?style=flat-square&logo=nestjs&logoColor=white" /></a>
> +  <a href="https://www.typescriptlang.org"><img alt="टाइप स्क्रिप्ट" src="https://img.shields.io/badge/-TypeScript-007ACC?style=flat-square&logo=typescript&logoColor=white" /></a>
> +  <a href="https://www.prisma.io"><img alt="प्रिज्मा" src="https://img.shields.io/badge/-Prisma-1B222D?style=flat-square&logo=prisma&logoColor=white" /></a>
> +  <a href="https://www.mongodb.com"><img alt="मोंगो डी बी" src="https://img.shields.io/badge/-MongoDB-47A248?style=flat-square&logo=mongodb&logoColor=white" /></a>
> +  <a href="https://www.postgresql.org"><img alt="पोस्टग्रेएसक्यूएल" src="https://img.shields.io/badge/-PostgreSQL-657991?style=flat-square&logo=postgresql&logoColor=white" /></a>
> +  <a href="https://www.mysql.com"><img alt="माई एसक्यूएल" src="https://img.shields.io/badge/-MySQL-00688F?style=flat-square&logo=mysql&logoColor=white" /></a>
> +</p>
> +
> +एपीआई जो इंडोनेशिया के **प्रशासनिक क्षेत्रों**, प्रांत, रीजेंसी, जिले से लेकर ग्राम स्तर तक की जानकारी प्रदान करता है। यह [संस्करण 1.1.0] से द्वीप डेटा भी प्रदान करता है (https://github.com/fityannugroho/idn-area/releases/tag/v1.1.0)।
>
> This link will not rendered well. Can you fix it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fityannugroho/idn-area/pull/194#pullrequestreview-1660111650>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A752EJ7RDMSWOE3T5ULIPJTX53GDPAVCNFSM6AAAAAA5UFVUGSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNRQGEYTCNRVGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-05 16:13 UTC, CharithaCS commented
Updated. please check.

2023-10-06 03:31 UTC, fityannugroho commented
We just updated the README especially on the section related to API documentation. So please update the translation to be match with the latest README (see #198).

You also need to update your fork branch using [Sync fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) to pull the updated workflow so that this PR can pass the checks.

2023-10-06 04:14 UTC, CharithaCS commented
Done!

On Fri, 6 Oct, 2023, 09:01 Fityan, ***@***.***> wrote:

> We just updated the README especially on the section related to API
> documentation. So please update the translation to be match with the latest
> README (see #198 <https://github.com/fityannugroho/idn-area/pull/198>).
>
> You also need to update your fork branch using Sync fork
> <https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork>
> to pull the updated workflow so that this PR can pass the checks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fityannugroho/idn-area/pull/194#issuecomment-1749936307>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A752EJ2ETIZ7OJBSYMTOFU3X553QJAVCNFSM6AAAAAA5UFVUGSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONBZHEZTMMZQG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-06 07:21 UTC, fityannugroho approved these changes

2023-10-06 07:22 UTC, merged