docs: add the Indonesia translation of README.md
fityannugroho/idn-area pull request #201
Opened 2023-10-09 13:32 UTC by tedante

## PR Checklist

Please check if your PR fulfills the following requirements:

> Put "x" to check

- [ x ] The commit message follows our [Contributing Guidelines](https://github.com/fityannugroho/idn-area/blob/main/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (**optional**, for bug fixes or features)
- [ x ] Docs have been added / updated (**optional**, for bug fixes or features)

## PR Type

What kind of change does this PR introduce?

> Please check any kind of changes that applies to this PR using "x"

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x ] Docs

## What is the current behavior?

> Please describe the current behavior that you are modifying, or link to a relevant issue.

Issue Number: #95 

## What is the new behavior?

Add Indonesia translation of README.md file

## Other information

Please kindly to reviewing my pull request
Thank you

2023-10-10 01:10 UTC, fityannugroho requested changes
Please fix it. Thanks for your effort.

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +[English](README.md) | [हिन्दी](docs/README_hi.md) | [Tagalog](docs/README_tl.md) | **Indonesia**
Link ke file lain salah. Gunakan relative path (lihat [artikel berikut](https://www.redhat.com/sysadmin/linux-path-absolute-relative)).

```suggestion
[English](../README.md) | [हिन्दी](README_hi.md) | [Tagalog](README_tl.md) | **Bahasa Indonesia**
```

Tolong disesuaikan juga kalau seterusnya ada link yang menuju ke file lain.

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +API yang memberikan informasi tentang **wilayah administratif Indonesia**, mulai dari tingkat provinsi, kabupaten, kecamatan, hingga tingkat desa. Dan juga menyediakan data pulau sejak [versi 1.1.0](
```suggestion
API yang menyediakan informasi tentang **wilayah administratif Indonesia**, mulai dari tingkat provinsi, kabupaten, kecamatan, hingga tingkat desa. API ini juga menyediakan data pulau sejak [versi 1.1.0](https://github.com/fityannugroho/idn-area/releases/tag/v1.1.0).
```

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +Dibuat dengan [NestJS framework](https://nestjs.com) dan ditulis dengan bahasa TypeScript. [Prisma](https://www.prisma.io) digunakan sebagai ORM untuk berinteraksi dengan berbagai macam databases (My
```suggestion
Dibuat dengan [NestJS framework](https://nestjs.com) dan ditulis dalam bahasa pemrograman TypeScript. [Prisma](https://www.prisma.io) digunakan sebagai ORM untuk berinteraksi dengan berbagai macam jenis database (MySQL, PostgreSQL, dan MongoDB).
```

Saya rasa lebih baik "bahasa pemrograman" agar lebih jelas.

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +> **⚠️ Upgrading to v3.0.0 ⚠️**
Perlu diterjemahkan

```suggestion
> **⚠️ Meningkatkan ke v3.0.0 ⚠️**
```

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +> Sejak [v3.0.0](https://github.com/fityannugroho/idn-area/releases/tag/v3.0.0), harus menggunakan **Node.js v18** atau versi yang lebih tinggi.
```suggestion
> Sejak [v3.0.0](https://github.com/fityannugroho/idn-area/releases/tag/v3.0.0), diperlukan **Node.js v18** atau versi yang lebih tinggi.
```

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +- [Panduan Awal](#panduan-awal)
Saya rasa "memulai" adalah terjemahan yang lebih tepat. Tolong ke bawahnya juga disesuaikan.

```suggestion
- [Memulai](#memulai)
```

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +- [Laporan Masalah](#laporan-masalah)
```suggestion
- [Melaporkan Masalah](#melaporkan-masalah)
```

Tolong ke bawahnya juga disesuaikan.

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +  - [Lapor Error](#lapor-error)
```suggestion
  - [Melaporkan Bug](#melaporkan-bug)
```

Tolong ke bawahnya juga disesuaikan.

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +  - [Pertanyaan](#pertanyaan)
```suggestion
  - [Mengajukan Pertanyaan](#mengajukan-pertanyaan)
```

Tolong ke bawahnya juga disesuaikan.

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +Tolong baca [panduan install](docs/installation.md) untuk menginstall dan menjalankan aplikasi ini.
```suggestion
Tolong baca [panduan instalasi](installation.md) untuk memasang dan menjalankan aplikasi ini.
```

Tolong perbaiki juga linknya.

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +Baca versi terbaru dokumentasi API di [halaman dokumentasi](https://idn-area.cyclic.app/docs). Dokumentasi ini otomatis dibuat menggunakan [`@nestjs/swagger`](https://docs.nestjs.com/openapi/introduc
```suggestion
Baca versi terbaru dokumentasi API di [halaman dokumentasi](https://idn-area.cyclic.app/docs). Dokumentasi ini dibuat secara otomatis menggunakan [`@nestjs/swagger`](https://docs.nestjs.com/openapi/introduction).
```

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +> Anda juga dapat mengakses dokumentasi di lokal anda dengan menjalankan aplikasi ini. (lihat [Panduan Awal](#panduan-awal)) dan buka http://localhost:3000/docs di internet browser.
```suggestion
> Anda juga dapat mengakses dokumentasinya di perangkat lokal Anda dengan menjalankan aplikasi ini (lihat [Memulai](#memulai)) dan buka http://localhost:3000/docs di browser Anda.
```

**Catatan:** Sesuai [Ejaan Bahasa Indonesia](https://ejaan.kemdikbud.go.id/eyd/penggunaan-huruf/huruf-kapital/#23-huruf-kapital-digunakan-sebagai-huruf-pertama-kata-penunjuk-hubungan-kekerabatan-seperti-bapak-ibu-kakak-dan-adik-serta-kata-atau-ungkapan-lain-termasuk-unsur-bentuk-ulang-utuh-yang-digunakan-sebagai-sapaan), kata "Anda" ditulis dengan **huruf awal kapital** baik di awal maupun di tengah kalimat.

Tolong ke bawahnya juga disesuaikan.

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +Untuk melaporkan error, silahkan buka isu baru dengan mengikuti [panduan](CONTRIBUTING.md#submitting-an-issue).
```suggestion
Untuk melaporkan bug, silahkan buka isu baru dengan mengikuti [panduan](CONTRIBUTING.md#submitting-an-issue).
```

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +Anda dapat mendukung proyek ini dengan berdonasi melalui [GitHub Sponsor](https://github.com/sponsors/fityannugroho), [Trakteer](https://trakteer.id/fityannugroho/tip), or [Saweria](https://saweria.c
```suggestion
Anda dapat mendukung proyek ini dengan berdonasi melalui [GitHub Sponsor](https://github.com/sponsors/fityannugroho), [Trakteer](https://trakteer.id/fityannugroho/tip), atau [Saweria](https://saweria.co/fityannugroho).
```

2023-10-10 01:10 UTC, fityannugroho commented on docs/README_id.md
> +Data yang kami gunakan menggunakan sumber yang resmi, dikelola oleh [**idn-area-data**](https://github.com/fityannugroho/idn-area-data) repositori dan didistribusikan sebagai sebuah [npm package](htt
```suggestion
Data yang kami gunakan menggunakan sumber yang resmi, dikelola di repositori [**idn-area-data**](https://github.com/fityannugroho/idn-area-data) dan didistribusikan sebagai sebuah [npm package](https://www.npmjs.com/package/idn-area-data).
```

2023-10-10 22:24 UTC, tedante commented
Oke thank you udah di review.
Akan segera diupdate

2023-10-11 14:30 UTC, tedante commented
Hi @fityannugroho , saya sudah menyesuaikan kembali readme-nya
Tolong di review kembali,
Thank you

2023-10-12 00:37 UTC, fityannugroho commented
> Hi @fityannugroho , saya sudah menyesuaikan kembali readme-nya Tolong di review kembali, Thank you

Sepertinya masih ada yang terlewat dari review sebelumnya. Tolong dicek kembali ya. Klik "Resolve conversation" kalau memang sudah di-fix.

2023-10-12 00:40 UTC, fityannugroho commented on docs/README_id.md
> +[English](README.md) | [हिन्दी](docs/README_hi.md) | [Tagalog](docs/README_tl.md) | **Indonesia**
Ini belum solve

2023-10-12 00:43 UTC, fityannugroho requested changes
Masih ada perbaikan yang terlewat dari review sebelumnya. Tolong cek kembali review sebelumnya.

2023-10-17 07:55 UTC, tedante commented
Baik @fityannugroho, sorry tentang hal yang terlewat.
Saya sudah perbaiki kembali untuk wording dan link-nya 
Tolong direview kembali
Terima kasih

2023-10-17 08:26 UTC, fityannugroho approved these changes
LGTM ⭐

2023-10-17 08:27 UTC, merged